CRUD DEMO/StudentRecordManagementSystem/Models/ErrorViewModel.cs
using System;

namespace StudentRecordManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD DEMO/StudentRecordManagementSystem/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace StudentRecordManagementSystem.Models
{
    public class Student
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Gender { get; set; }

        [Required]

        public int Age { get; set; }

        [Required]
        public double Percentage { get; set; }
    }
}

CRUD DEMO/StudentRecordManagementSystem/Models/studentDAL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;

using System.Data.SqlClient;
using System.Configuration;

namespace StudentRecordManagementSystem.Models
{
    public class StudentDAL
    {
        string connectionString = "Data Source=DESKTOP-1C9S6B8;Initial Catalog=StudentRecordDB;Integrated Security=False; Persist Security Info = False; User ID = sa; password = hrhk;";
        //To get all records.
        public IEnumerable<Student> GetStudents()
        {
            List<Student> stuList = new List<Student>();

            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SP_GetStudents", con);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Student student = new Student();
                    student.Id = Convert.ToInt32(dr["Id"].ToString());
                    student.Name = dr["Name"].ToString();
                    student.Gender = dr["Gender"].ToString();
                    student.Age = Convert.ToInt32(dr["Age"].ToString());
                    student.Percentage = Convert.ToDouble(dr["Percentage"].ToString());
                    stuList.Add(student);

                }
                con.Close();
            }
            return stuList;
        }

        //To insert a student record.
        public void AddStudent(Student student)
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SP_InsertStudent", con);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@name", student.Name);
                cmd.Parameters.AddWithValue("@gender", student.Gender);
                cmd.Parameters.AddWithValue("@age", student.Age);
                cmd.Parameters.AddWithValue("@percentage", student.Percentage);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
            }
        }

        //To Update Student Record.

        public void UpdateStudent(Student student)
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SP_UpdateStudent", con);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", student.Id);
                cmd.Parameters.AddWithValue("@name", student.Name);
                cmd.Parameters.AddWithValue("@gender", student.Gender);
                cmd.Parameters.AddWithValue("@age", student.Age);
                cmd.Parameters.AddWithValue("@percentage", student.Percentage);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
            }
        }

        //To Delete Student Record.

        public void DeleteStudent(int id)
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SP_DeleteStudent", con);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
            }
        }

        //Get Student Record By Id.

        public Student GetStudentById(int id)
        {
            Student student = new Student();

            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SP_GetStudentById", con);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {

                    student.Id = Convert.ToInt32(dr["Id"].ToString());
                    student.Name = dr["Name"].ToString();
                    student.Gender = dr["Gender"].ToString();
                    student.Age = Convert.ToInt32(dr["Age"].ToString());
                    student.Percentage = Convert.ToDouble(dr["Percentage"].ToString());

                }
                con.Close();
            }
            return student;
        }
    }
}

CRUD DEMO/StudentRecordManagementSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentRecordManagementSystem.Models;

namespace StudentRecordManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD DEMO/StudentRecordManagementSystem/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentRecordManagementSystem.Models;

namespace StudentRecordManagementSystem.Controllers
{
    public class StudentController : Controller
    {
        StudentDAL studentDAL = new StudentDAL();
        public IActionResult Index()
        {
            List<Student> stud = new List<Student>();
            stud = studentDAL.GetStudents().ToList();
            return View(stud);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] Student student)
        {
            if (ModelState.IsValid)
            {
                studentDAL.AddStudent(student);
                return RedirectToAction("Index");
            }
            return View(student);
        }



        public IActionResult Edit(int id)
        {
            Student student = studentDAL.GetStudentById(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(int id, [Bind] Student student)
        {
            if (ModelState.IsValid)
            {
                studentDAL.UpdateStudent(student);
                return RedirectToAction("Index");
            }
            return View(studentDAL);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Student student = studentDAL.GetStudentById(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        public IActionResult Delete(int id)
        {
            Student student = studentDAL.GetStudentById(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost , ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public IActionResult DeleteStudent(int id)
        {
            studentDAL.DeleteStudent(id);
            return RedirectToAction("Index");
        }
    }
}

CRUD DEMO/StudentRecordManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD DEMO/StudentRecordManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentRecordManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentRecordManagementSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StudentRecordManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CRUD DEMO/StudentRecordManagementSystem/Views/Student/Create.cshtml
@model StudentRecordManagementSystem.Models.Student
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control">
                    <option value="">---Select Gender---</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control">
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Percentage" class="control-label"></label>
                <input asp-for="Percentage" class="form-control">
                <span asp-validation-for="Percentage" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success">
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>

CRUD DEMO/StudentRecordManagementSystem/Views/Student/Delete.cshtml
@model StudentRecordManagementSystem.Models.Student
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>
<div>
    <h4>STUDENT INFORMAION</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Name)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Gender)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Age)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Percentage)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Percentage)
        </dt>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id">
        <input type="submit" value="Delete" class="btn-danger" />
        <a asp-action="Index">Back to list</a>
        </form>
</div>

CRUD DEMO/StudentRecordManagementSystem/Views/Student/Details.cshtml
@model StudentRecordManagementSystem.Models.Student
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h2>Details</h2>

<div>
    <h4>STUDENT INFORMAION</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Name)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Gender)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Age)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Percentage)
        </dt>
        <dt>
            @Html.DisplayFor(model => model.Percentage)
        </dt>
    </dl>
    </div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a asp-action="Index">Back to List</a>
    </div>

CRUD DEMO/StudentRecordManagementSystem/Views/Student/Edit.cshtml
@model StudentRecordManagementSystem.Models.Student
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<h4>Student Edit</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control">
                    <option value="">---Select Gender---</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control">
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Percentage" class="control-label"></label>
                <input asp-for="Percentage" class="form-control">
                <span asp-validation-for="Percentage" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success">
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>

CRUD DEMO/StudentRecordManagementSystem/Views/Student/Index.cshtml
@model IEnumerable<StudentRecordManagementSystem.Models.Student>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>

@*To display Student Records.*@
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Percentage)
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => student.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => student.Gender)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => student.Age)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => student.Percentage)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@student.Id">Edit</a>
                    <a asp-action="Details" asp-route-id="@student.Id">Details</a>
                    <a asp-action="Delete" asp-route-id="@student.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>